ColumnChart сщьзщтут
js-tasks-ru/js-20210615_gorovikovkg pull request #3
Opened 2021-06-26 00:00 UTC by NikolayGorovikov

2021-06-26 00:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-26 00:21 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-06-28 21:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    constructor(obj = {}) {
было бы неплохо навести порядок в методаx. Обычно `constructor` используют для инициализации свойств класса и вызова дальнейших методов, а создание самого элемента выносят в отдельный метод: `render`, `createElement` или какое-то другое название

2021-06-28 21:59 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    update({data = [], label = "untitled", value = 0, link, formatHeading = (data) => data}){
метод который создает разметку элемента не соответствует имени `update` 
`update` - это обновление, а тут у нас создание

2021-06-28 22:00 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      delete this.element;
`delete` удалит поле из объекта, а нам нужно очистить объект, следует использовать `this.element = null`

2021-06-28 22:01 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +function makeColons(data){
почему данный метод находится за пределами класса?

2021-06-28 22:01 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    result+=`<div style="--value: ${value}" data-tooltip="${percent}"></div>`
при создании шаблона компонента лучше использовать `map` - обойти весь массив данных и после привести данный массив к строке

2021-06-28 22:03 UTC, dosandk requested changes
попробуйте разбить логику `update` на несколько логических частей и вынести ее в разные методы, также необходимо дать ответ на вопрос

2021-06-28 23:34 UTC, NikolayGorovikov commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +function makeColons(data){
Ну я подумал что эта функция вряд ли будет использована отдельно, то есть скорее всего никто не захочет отдельно сгенерировать DOM строку по определенному массиву и если добавить ее в класс то она может запутать того кто будет с ним работать, но я могу ошибаться

2021-06-29 00:00 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-06-29 12:57 UTC, dosandk approved these changes

2021-06-29 12:57 UTC, merged