SortableTable V1
js-tasks-ru/js-20210615_gorovikovkg pull request #4
Opened 2021-07-03 16:08 UTC by NikolayGorovikov

2021-07-03 16:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-03 21:32 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-07-03 21:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-03 23:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-04 00:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-04 01:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-04 16:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-07-05 19:24 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this?.element?.remove();
зачем проверка `this?` есть ли случай когда `this` не определен?

2021-07-05 19:25 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static removeMessage() {
почему данный метод статический?

2021-07-05 19:25 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.duration = duration;
почему присваивается значение `duration` внутри данного метода, а не внутри `constructor`?

2021-07-05 19:27 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    this.headers = [];
помните на занятии мы обсуждали что значения которые не зависят от входных аргументов стоит вынести в `class-properties`?
```
  subElements = {};
  ...
  constructor (...) { ... 
```
```

2021-07-05 19:29 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    this.element.innerHTML = `<div data-element="productsContainer" class="products-list__container">
почему инициализация значений и конструирование элементов происходит в одном методе?
может стоит разделить этот процесс на разные методы, используйте подход single responsibility - каждый метод отвечает только за одно действие

2021-07-05 19:31 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    //Обработка клика ...
зачес здесь находится данный комментарий, не проще ли вынести данную логику в отдельный метод?

2021-07-05 19:33 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  constructor() {
пожалуйста разбейте данный метод на логические операции и выделите их в отдельные методы

2021-07-05 19:34 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    this.from = Number(((parseFloat(this.subElements.range.style.left))/this.subElements.rangeInner.getBoundingClientRect().width*(this.max - this.min)+this.min).toFixed(0));
что происходит в данной строке?
может лучше разбить данное выражение на несколько?

2021-07-05 19:34 UTC, dosandk requested changes
Пожалуйста дайте ответы на вопросы.
Самая большая проблема в Ваших решениях - это нагромождения кода в одном методе, это нужно поправить

2021-07-05 21:11 UTC, NikolayGorovikov commented on 05-dom-document-loading/1-notification/index.js
> +  static removeMessage() {
Я решил что раз мы храним текущее сообщение в статическом свойстве класса, то стоит записать и функцию которая будет статическим свойством что бы она взаимодействовала с классом через this и была как бы в одной экосистеме с классом а не с экземпляром

2021-07-05 21:17 UTC, NikolayGorovikov commented on 05-dom-document-loading/1-notification/index.js
> +    this.duration = duration;
Стоило сделать это в конструкторе,  ведь тогда теряется смысл метода createInner

2021-07-05 21:19 UTC, NikolayGorovikov commented on 05-dom-document-loading/1-notification/index.js
> +    this?.element?.remove();
Согласен что она тут не нужна, хотел сделать проверку на element и случайно сделал еще и на this

2021-07-05 21:23 UTC, NikolayGorovikov commented on 06-events-practice/1-sortable-table-v2/index.js
> +    //Обработка клика ...
Согласен с вами, исправлю

2021-07-06 16:14 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.duration = duration;
good 👍 
да, `constructor` как раз и предназначен для инициализации значение

2021-07-08 20:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-09 14:22 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static removeMessage() {
тогда это проблема, так как `this` внутри статического метода не ссылается на объект который будет создан с помощью класса:
```
class Component {
  static getName () => console.log(this.username);

  constructor () {
    this.username = 'John'
  }
}

Component.getName(); // undefined
```

2021-07-12 02:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-12 14:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-12 15:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-15 23:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-16 12:59 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +//     const isDone = new Promise((resolve, reject)=>{
в данном решении нужно убрать обертку `new Promise`

2021-07-16 12:59 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +//       this.create(id, order, url, headersConfig, resolve, reject);
функцию `this.create` следует переименовать, тесты ожидают что в решении будет метод `render` и он будет асинхронным

2021-07-16 13:33 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +//   async create(id, order, url, headersConfig, onSuccess, onFail){
параметры `onSuccess` и `onFail` здесь следует убрать

2021-07-16 13:34 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +//       this.subElements.body = this.makeBody(await this.getData(0, 30, order, id, url));
`this.subElements.body` следует сконструировать до `await this.getData`

2021-07-17 02:34 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-07-18 02:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-18 02:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-18 23:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-07-19 00:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-20 11:06 UTC, dosandk approved these changes

2021-07-20 11:08 UTC, merged